#!/bin/bash

#echo hello
#Rscript simulation.R 100 10 0.8
#for i in 0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1 
#do
#	for j in {200..2000..200} 
#	do
	
#		Rscript genePool_sim.R 30000 50 $i $j
#	done	
#done

for i in 0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1 
do
		Rscript genePool_sim.R 30000 50 $i 1558
done
